export const projects = [
  {
    title: 'E-Commerce & Web Page',
    description: "Web page and e-commerce destinated to distribute office implements. It also shows the full products and services brochure of teh company. Completely designed using wordpress and woocommerce templates. (Currently under renovation)",
    image: '/images/2.jpg',
    tags: ['WordPress', 'HTML', 'JavaScript', 'css'],
    source: 'https://serviciosatlas.com.co/',
    visit: 'https://github.com/jmrobles10/AtlasServicesWebPage',
    id: 0,
  },
  {
    title: 'Luces Apagadas',
    description: "My very first real Java Project. 'Luces Apagadas' is a Java based game, with the goal of switch off all the lights, by clicking on each window and change the state of the adjacent windows, from on to off and vice versa.",
    image: '/images/1.jpg',
    tags: ['Java', 'Eclipse'],
    source: 'https://mateorobles.com/#projects',
    visit: 'https://github.com/jmrobles10/LucesApagadas-2ndVersion',
    id: 1,
  },
  {
    title: 'REST API - Game Saver',
    description: "Web App using Angular 7, Node.js and MySQL. This code corresponds to a REST API using Node.js along with TypeScript, to use with a front-end application, implementing angular and some JavaScript modules.",
    image: '/images/3.jpg',
    tags: ['Angular 7', 'Node.js', 'MySQL', 'JavaScript'],
    source: 'https://mateorobles.com',
    visit: 'https://github.com/jmrobles10/SaveYourGame',
    id: 2,
  },
  {
    title: 'Portfolio',
    description: "This is a code repository for the current portfolio. In this project, I built a responsive personal portfolio using React and Next.js",
    image: '/images/4.jpg',
    tags: ['React', 'Next.js'],
    source: 'https://mateorobles.com',
    visit: 'https://github.com/jmrobles10/MyPortfolio',
    id: 3,
  },
  {
    title: 'Save Your Links',
    description: "This is a code repository for a link saver. In this project, I built a web application from the Backend to the Frontend, using Node.js, MongoDB, Express and another JavaScript Technologies. This is a simple CRUD de Nodejs, including a LogIn and a SignUp using MongoDB, also using athentication for the users. It was stylized using Bootstrap5 and css.",
    image: '/images/5.jpg',
    tags: ['Node.js', 'MySQL', 'Express', 'Angular 7'],
    source: 'https://mateorobles.com',
    visit: 'https://github.com/jmrobles10/SaveYourLinks',
    id: 3,
  },
  {
    title: 'Z-Land -Coming Soon-',
    description: "Current project making of a Android game using Unity and C#.",
    image: '/images/6.jpg',
    tags: ['Unity'],
    source: 'https://mateorobles.com',
    visit: 'https://mateorobles.com',
    id: 4,
  },
];

export const TimeLineData = [
  { year: 2015, text: 'Started my journey as a Mechanical Engineerign Student', },
  { year: 2018, text: 'Founded Atlas Services as a services provider to companies', },
  { year: 2019, text: 'Developing my first web page and e-commerce. Start to learn some Programming Languajues', },
  { year: 2021, text: 'Graduated as a Mechanical Engineer ', },
  { year: 2022, text: 'Launched my own web portfolio "mateorobles.com"', },
];